name: PHP Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: PHP Lint
      uses: michaelw90/PHP-Lint@2.1.0

